---
name: Erlang CI

on: [push]
# on:
#   push:
#     branches:
#       - master
#   pull_request:
#     branches:
#       - master
  
#   workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    name: OTP ${{matrix.otp}}
    strategy:
      matrix:
        otp: [
            "20.0", "20.1.7", "20.3.8.22",
            "21.0.9", "21.1.4", "21.2.7", "21.3.8.1",
            "22.0.7", "22.2.8", "22.3.4",
            "23.1", "23.2"
          ]
    steps:
      - uses: actions/checkout@v2.0.0
      - uses: gleam-lang/setup-erlang@v1.1.3
        with:
          otp-version: ${{matrix.otp}}
      - run: rebar3 xref
      - run: rebar3 eunit
      - run: rebar3 dialyzer
