---
name: Erlang CI

on: [push]
# on:
#   push:
#     branches:
#       - master
#   pull_request:
#     branches:
#       - master
  
#   workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-18.04
    name: OTP ${{matrix.otp}}
    strategy:
      matrix:
        otp: [
            '19.3.6',
            '20.3.8.26',
            '21.3.8.16',
            '22.3.4.2',
            '23.0.2',
            '24.0'
          ]
    steps:
      - uses: actions/checkout@v2
      - uses: gleam-lang/setup-erlang@v1.1.2
        with:
          otp-version: ${{matrix.otp}}
      # - run: rebar3 compile
      # - run: rebar3 xref
      - run: rebar3 eunit
      - run: rebar3 dialyzer
